{application,ad_2,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{ad_2_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[ad_2,ad_2_app,ad_2_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
